# Generated by Django 4.2.18 on 2025-01-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Όνομα')),
                ('last_name', models.CharField(max_length=100, verbose_name='Επώνυμο')),
                ('father_name', models.CharField(max_length=100, verbose_name='Πατρώνυμο')),
                ('location', models.CharField(max_length=100, verbose_name='ΕΔΡΑ')),
                ('gender', models.CharField(max_length=50, verbose_name='Φύλο')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Οικογενειακή Κατάσταση')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γέννησης')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Τηλέφωνο Κινητό')),
                ('landline_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Τηλέφωνο Σταθερό')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='ΑΦΜ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Διεύθυνση')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Τμήμα')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Αρμοδιότητες')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ειδικότητα-Πτυχίο')),
                ('degree_available', models.FileField(blank=True, null=True, upload_to='degrees/', verbose_name='Διαθέσιμο πτυχίο')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Μισθός')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('hiring_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πρόσληψης')),
                ('employee_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Κατάσταση Εργαζομένου')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λύσης συνεργασίας')),
                ('medical_exams', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ιατρικές Εξετάσεις')),
                ('medical_exams_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Ιατρικών Εξετάσεων')),
                ('medical_exams_renewal_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Ανανέωσης Ιατρικών Εξετάσεων')),
                ('safety_passport', models.CharField(blank=True, max_length=50, null=True, verbose_name='Safety Passport')),
                ('safety_passport_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Safety Passport')),
                ('safety_passport_renewal_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Ανανέωσης Safety Passport')),
                ('certifications_seminars', models.TextField(blank=True, null=True, verbose_name='Πιστοποιήσεις-Σεμινάρια')),
            ],
        ),
    ]
