# Generated by Django 4.2.18 on 2025-01-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0007_dailyattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('basic_info', 'date')},
        ),
    ]
