# Generated by Django 4.2.18 on 2025-01-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0010_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='egnatia_app.department', verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='egnatia_app.group', verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='egnatia_app.region', verbose_name='Region'),
            preserve_default=False,
        ),
    ]
