# Generated by Django 4.2.18 on 2025-01-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0011_employee_department_employee_group_employee_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='group',
        ),
        migrations.CreateModel(
            name='GroupDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egnatia_app.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egnatia_app.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='departments',
            field=models.ManyToManyField(related_name='groups', through='egnatia_app.GroupDepartment', to='egnatia_app.department'),
        ),
    ]
