# Generated by Django 4.2.18 on 2025-02-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0018_alter_customer_total_cabins_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogram',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='egnatia_app.customer'),
            preserve_default=False,
        ),
    ]
