# Generated by Django 4.2.18 on 2025-02-05 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0020_remove_customer_syfmonitiko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
    ]
