# Generated by Django 4.2.18 on 2025-02-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0021_alter_dailyattendance_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailyattendance',
            constraint=models.UniqueConstraint(fields=('basic_info', 'attendance_report'), name='unique_employee_attendance_report'),
        ),
    ]
