# Generated by Django 4.2.18 on 2025-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_1', models.CharField(max_length=50, verbose_name='PERIOD 1')),
                ('study_1', models.TextField(blank=True, null=True, verbose_name='STUDY 1')),
                ('period_2', models.CharField(max_length=50, verbose_name='PERIOD 2')),
                ('study_2', models.TextField(blank=True, null=True, verbose_name='STUDY 2')),
                ('period_3', models.CharField(max_length=50, verbose_name='PERIOD 3')),
                ('study_3', models.TextField(blank=True, null=True, verbose_name='STUDY 3')),
            ],
        ),
    ]
