# Generated by Django 4.2.18 on 2025-01-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0002_studies'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_1_start', models.DateField(blank=True, null=True, verbose_name='PERIOD 1 Start')),
                ('period_1_end', models.DateField(blank=True, null=True, verbose_name='PERIOD 1 End')),
                ('work_1', models.TextField(blank=True, null=True, verbose_name='WORK 1')),
                ('period_2_start', models.DateField(blank=True, null=True, verbose_name='PERIOD 2 Start')),
                ('period_2_end', models.DateField(blank=True, null=True, verbose_name='PERIOD 2 End')),
                ('work_2', models.TextField(blank=True, null=True, verbose_name='WORK 2')),
                ('period_3_start', models.DateField(blank=True, null=True, verbose_name='PERIOD 3 Start')),
                ('period_3_end', models.DateField(blank=True, null=True, verbose_name='PERIOD 3 End')),
                ('work_3', models.TextField(blank=True, null=True, verbose_name='WORK 3')),
                ('period_4_start', models.DateField(blank=True, null=True, verbose_name='PERIOD 4 Start')),
                ('period_4_end', models.DateField(blank=True, null=True, verbose_name='PERIOD 4 End')),
                ('work_4', models.TextField(blank=True, null=True, verbose_name='WORK 4')),
                ('period_5_start', models.DateField(blank=True, null=True, verbose_name='PERIOD 5 Start')),
                ('period_5_end', models.DateField(blank=True, null=True, verbose_name='PERIOD 5 End')),
                ('work_5', models.TextField(blank=True, null=True, verbose_name='WORK 5')),
            ],
        ),
    ]
