# Generated by Django 4.2.18 on 2025-01-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0003_workexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
                ('seminar_training_name', models.CharField(max_length=255)),
                ('period', models.CharField(choices=[('PERIOD 1', 'PERIOD 1'), ('PERIOD 2', 'PERIOD 2'), ('PERIOD 3', 'PERIOD 3'), ('PERIOD 4', 'PERIOD 4'), ('PERIOD 5', 'PERIOD 5')], max_length=50)),
                ('topics', models.TextField()),
            ],
        ),
    ]
