# Generated by Django 4.2.18 on 2025-01-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0004_seminartraining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminartraining',
            name='period',
        ),
        migrations.RemoveField(
            model_name='seminartraining',
            name='seminar_training_name',
        ),
        migrations.RemoveField(
            model_name='seminartraining',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='seminartraining',
            name='year',
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='basic_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_training', to='egnatia_app.basicinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_1_end',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 1 End'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_1_start',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 1 Start'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_2_end',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 2 End'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_2_start',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 2 Start'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_3_end',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 3 End'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_3_start',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 3 Start'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_4_end',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 4 End'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_4_start',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 4 Start'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_5_end',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 5 End'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='period_5_start',
            field=models.DateField(blank=True, null=True, verbose_name='PERIOD 5 Start'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='seminar_1',
            field=models.TextField(blank=True, null=True, verbose_name='Seminar 1 Topics'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='seminar_2',
            field=models.TextField(blank=True, null=True, verbose_name='Seminar 2 Topics'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='seminar_3',
            field=models.TextField(blank=True, null=True, verbose_name='Seminar 3 Topics'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='seminar_4',
            field=models.TextField(blank=True, null=True, verbose_name='Seminar 4 Topics'),
        ),
        migrations.AddField(
            model_name='seminartraining',
            name='seminar_5',
            field=models.TextField(blank=True, null=True, verbose_name='Seminar 5 Topics'),
        ),
        migrations.AddField(
            model_name='studies',
            name='basic_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='egnatia_app.basicinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='basic_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='egnatia_app.basicinfo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OtherLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255, verbose_name='Language Name')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_languages', to='egnatia_app.basicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OtherKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, verbose_name='Skill Name')),
                ('basic_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_knowledge', to='egnatia_app.basicinfo')),
            ],
        ),
    ]
