# Generated by Django 4.2.18 on 2025-01-23 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0006_otherknowledge_skill_2_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='ΗΜΕΡΟΜΗΝΙΑ')),
                ('presence', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, verbose_name='ΠΑΡΟΥΣΙΑ')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ΠΟΣΟΤΗΤΑ')),
                ('po_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='PO NUMBER')),
                ('site_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='SITE ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='SITE NAME')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='egnatia_app.basicinfo')),
            ],
        ),
    ]
