# Generated by Django 4.2.18 on 2025-01-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0012_remove_department_group_groupdepartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Expenses'),
        ),
    ]
