# Generated by Django 4.2.18 on 2025-01-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0014_cancel_infooldnew_wfm_sr_infocodesr_info_closedssr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='sr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egnatia_app.sr'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='wfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='egnatia_app.wfm'),
        ),
        migrations.AlterField(
            model_name='cancel',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egnatia_app.sr'),
        ),
        migrations.AlterField(
            model_name='wfm',
            name='sr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egnatia_app.sr'),
        ),
    ]
