# Generated by Django 4.2.18 on 2025-01-28 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0015_alter_assign_sr_alter_assign_wfm_alter_cancel_sr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sr',
            old_name='code',
            new_name='apartment_floor',
        ),
        migrations.RenameField(
            model_name='sr',
            old_name='status',
            new_name='building_id',
        ),
        migrations.RenameField(
            model_name='sr',
            old_name='unknown1',
            new_name='building_task_type',
        ),
        migrations.RenameField(
            model_name='sr',
            old_name='unknown2',
            new_name='sub',
        ),
        migrations.AddField(
            model_name='sr',
            name='sub_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sr',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sr',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sr',
            name='sr_code',
            field=models.IntegerField(unique=True),
        ),
    ]
