# Generated by Django 4.2.18 on 2025-02-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0016_rename_code_sr_apartment_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('total_meters_assigned', models.PositiveIntegerField(default=0)),
                ('total_freatio_assigned', models.PositiveIntegerField(default=0)),
                ('total_cabins_assigned', models.PositiveIntegerField(default=0)),
                ('total_catheta_assigned', models.PositiveIntegerField(default=0)),
                ('total_meters_done', models.PositiveIntegerField(default=0)),
                ('total_freatio_done', models.PositiveIntegerField(default=0)),
                ('total_cabins_done', models.PositiveIntegerField(default=0)),
                ('total_catheta_done', models.PositiveIntegerField(default=0)),
                ('syfmonitiko', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='total_cabins_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_cabins_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_catheta_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_catheta_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_freatio_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_freatio_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_meters_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_meters_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_cabins_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_cabins_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_catheta_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_catheta_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_freatio_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_freatio_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_meters_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='total_meters_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_pdf_file', models.FileField(blank=True, null=True, upload_to='daily_programs/')),
                ('total_meters_assigned', models.PositiveIntegerField(default=0)),
                ('total_freatio_assigned', models.PositiveIntegerField(default=0)),
                ('total_cabins_assigned', models.PositiveIntegerField(default=0)),
                ('total_catheta_assigned', models.PositiveIntegerField(default=0)),
                ('total_meters_done', models.PositiveIntegerField(default=0)),
                ('total_freatio_done', models.PositiveIntegerField(default=0)),
                ('total_cabins_done', models.PositiveIntegerField(default=0)),
                ('total_catheta_done', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='egnatia_app.group')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='egnatia_app.region')),
            ],
        ),
        migrations.CreateModel(
            name='AssignJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.PositiveIntegerField(default=0)),
                ('freatio', models.PositiveIntegerField(default=0)),
                ('cabins', models.PositiveIntegerField(default=0)),
                ('katheta', models.PositiveIntegerField(default=0)),
                ('meters_done', models.PositiveIntegerField(default=0)),
                ('freatio_done', models.PositiveIntegerField(default=0)),
                ('cabins_done', models.PositiveIntegerField(default=0)),
                ('katheta_done', models.PositiveIntegerField(default=0)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='egnatia_app.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='egnatia_app.group')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='egnatia_app.region')),
            ],
        ),
    ]
