# Generated by Django 4.2.18 on 2025-02-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0017_customer_group_total_cabins_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_cabins_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_cabins_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_catheta_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_catheta_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_freatio_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_freatio_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_meters_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_meters_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_cabins_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_cabins_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_catheta_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_catheta_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_freatio_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_freatio_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_meters_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_meters_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_cabins_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_cabins_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_catheta_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_catheta_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_freatio_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_freatio_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_meters_assigned',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='total_meters_done',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
