# Generated by Django 4.2.18 on 2025-02-05 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egnatia_app', '0019_dailyprogram_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='syfmonitiko',
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='presence',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='site_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='egnatia_app.group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='attendance_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='egnatia_app.attendancereport'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendance',
            unique_together={('basic_info', 'attendance_report')},
        ),
    ]
