# Generated by Django 4.2.18 on 2025-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("egnatia_app", "0022_alter_dailyattendance_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_photos/",
                verbose_name="Employee Photo",
            ),
        ),
    ]
